/*
* Action types
*/

export const FETCH_TYPES_PENDING = 'FETCH_TYPES_PENDING';
export const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS';
export const FETCH_TYPES_ERROR = 'FETCH_TYPES_ERROR';


export const FETCH_MOVES_PENDING = 'FETCH_MOVES_PENDING';
export const FETCH_MOVES_SUCCESS = 'FETCH_MOVES_SUCCESS';
export const FETCH_MOVES_ERROR = 'FETCH_MOVES_ERROR';


export const FETCH_REGIONS_PENDING = 'FETCH_REGIONS_PENDING';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_ERROR = 'FETCH_REGIONS_ERROR';


export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'
export const SEARCH = 'SEARCH';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const FILTER = 'FILTER';

export const FETCH_POKEMONS_PENDING = 'FETCH_POKEMONS_PENDING';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_ERROR = 'FETCH_POKEMONS_ERROR';

export const FETCH_POKEMON_PENDING = 'FETCH_POKEMON_PENDING';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_ERROR = 'FETCH_POKEMON_ERROR';

export const UPDATE_PAGE_SIZE = 'UPDATE_PAGE_SIZE';
export const FIRST_PAGE = 'FIRST_PAGE';
export const LAST_PAGE = 'LAST_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';

